import { MsjBienvenida } from '../modelos/msj-bienvenida';

export const MSJBIENVENIDA: MsjBienvenida[] = [
  new MsjBienvenida(1, `Cuando no se puede lo que se quiere, hay que querer lo que se puede.- Terencio`),
  new MsjBienvenida(2, `Es mejor dar muchos pasos pequeños en la buena dirección, que hacer un gran salto adelante para terminar cayendo hacia atrás.- Proverbio Chino`),
  new MsjBienvenida(3, `Comienza haciendo lo que es necesario, después lo que es posible y de repente estarás haciendo lo imposible.- San Francisco de Asis`),
  new MsjBienvenida(4, `Todas las cosas serán producidas en superior cantidad y calidad, y con mayor facilidad, cuando cada hombre trabaje en una sola ocupación, de acuerdo con sus dones naturales, y en el momento adecuado, sin inmiscuirse en nada más.- Platón`),
  new MsjBienvenida(5, `La forma de empezar es dejar de hablar y empezar a hacerlo.- Walt Disney`),
  new MsjBienvenida(6, `Tu trabajo va a llenar buena parte de tu vida, y la única manera de estar realmente satisfecho contigo mismo es hacer lo que creas que es un trabajo fantástico. Y la única manera de hacer un trabajo fantástico es amar lo que haces. Y si todavía no lo has encontrado, sigue buscando. No te rindas. Cuando lo encuentres, te darás cuenta, desde lo más profundo de tu corazón, que lo has encontrado.- Steve Jobs`),
  new MsjBienvenida(7, `La gente a menudo comentan que soy muy afortunado. La suerte es importante sólo en la medida en tener la oportunidad de venderte a ti mismo en el momento oportuno. Después de eso, usted tiene que tener talento y saber cómo usarlo.- Frank Sinatra`),
  new MsjBienvenida(8, `No es que yo sea tan inteligente, es solo que me quedo con los problemas más tiempo.- Albert Einstein`),
  new MsjBienvenida(9, `Cree en ti mismo! ¡Ten fe en tus habilidades! Si no tienes una confianza razonable y humilde, en tus capacidades, no podrás tener éxito o ser feliz.- Norman Vincent Peale`),
  new MsjBienvenida(10, `Los buenos consejos que me dan sólo me sirven si son traspasarlos a otros.- Oscar Wilde`),
  new MsjBienvenida(11, `El que no tenga el coraje suficiente para tomar riesgos no conseguirá nada en la vida.- Muhammad Ali`),
  new MsjBienvenida(12, `Es mejor permanecer callado y parecer tonto que hablar y despejar las dudas definitivamente.-  Mark Twain`),
  new MsjBienvenida(13, `Si amas tu vida, no malgaste tu tiempo, pues de esa materia está hecha.- Benjamin Franklin`),
  new MsjBienvenida(14, `No hay nada tan inútil como hacer con gran eficiencia algo que no debería haberse hecho en absoluto.- Peter Druker`),
  new MsjBienvenida(15, `El problema de no hacer nada es que nunca sabes cuándo has terminado.- Groucho Marx`),
  new MsjBienvenida(16, `El pensamiento es útil cuando incita a la acción, y un obstáculo cuando la sustituye.- Bill Raeder`),
  new MsjBienvenida(17, `Has primero el trabajo duro. Los trabajos fáciles se resolverán por sí mismos.- Dale Carnegie`),
  new MsjBienvenida(18, `El trabajo se expande hasta llenar el tiempo de que se dispone para su realización.- Cyril Northcote Parkinson`),
  new MsjBienvenida(19, `Nunca vas a encontrar tiempo para nada. Si quieres tener tiempo debes reservártelo.- Charles Buxton`),
  new MsjBienvenida(20, `Si no fuera por el último minuto, muchas cosas no se acabarían completando.- Michael S. Traylor`),
  new MsjBienvenida(21, `Lo que no se empieza nunca tendrá un final.- Johann Wolfgang von Goethe`),
  new MsjBienvenida(22, `Una onza de acción vale una tonelada de teoría.- Ralph Waldo Emerson`),
  new MsjBienvenida(23, `No me voy a limitar a mí misma sólo porque otras personas no aceptarán el hecho de que yo puedo hacer otra cosa.- Dolly Parton`),
  new MsjBienvenida(24, `El destino no es cuestión de casualidad, sino cuestión de elección. No es algo a lo que se deba esperar, sino algo a conseguir.- Jeremy Kitson`),
  new MsjBienvenida(25, `Elige un trabajo que te guste, y nunca tendrás que volver a trabajar en tu vida.- Confucio`),
  new MsjBienvenida(26, `Cuando dejas de soñar dejas de vivir.- Malcolm Forbes`),
  new MsjBienvenida(27, `El realismo es para pesimistas. Un optimista crea su propia realidad.- David Harley`),
  new MsjBienvenida(28, `Si puedes soñarlo, puedes hacerlo.- Walt Disney`),
  new MsjBienvenida(29, `Tener grandes expectativas es la clave de todo.- Sam Walton`),
  new MsjBienvenida(30, `El hombre que no tiene imaginación no tiene alas.- Muhammad Ali`),
  new MsjBienvenida(31, `Quiero hacerlo porque quiero hacerlo.- Amelia Earhart`),
  new MsjBienvenida(32, `El mejor uso de la vida es dedicarla a algo que la sobreviva.- William James`),
  new MsjBienvenida(33, `Puedo aceptar el fracaso, todos fracasan en algo. Pero no puedo aceptar no intentarlo.- Michael Jordan`),
  new MsjBienvenida(34, `Los ganadores nunca abandonan y los que abandonan nunca ganan.- Vince Lombardi`),
  new MsjBienvenida(35, `Uno de los mayores errores que comete la gente es intentar forzarse a tener interés por algo. Tú no eliges tus pasiones; tus pasiones te eligen a ti.- Jeff Bezos`),
  new MsjBienvenida(36, `Un líder es alguien que conoce el camino, anda el camino, y muestra el camino.- John C. Maxwell`),
  new MsjBienvenida(37, `Cuanto más tiempo pase sin que actúes más dinero estás dejando de ganar.- Carrie Wilkerson`),
  new MsjBienvenida(38, `El éxito no está en vencer siempre sino en no desanimarse nunca. – Napoleón Bonaparte`),
  new MsjBienvenida(39, `Él éxito no tiene que ver con la cantidad que tenemos, sino con la persona que somos. – Jim Rohn`),
  new MsjBienvenida(40, `Para conseguir el éxito, tu deseo de éxito debe ser mayor que tu miedo al fracaso.`),
  new MsjBienvenida(41, `No mido el éxito de un hombre por la altura que es capaz de subir, sino por lo alto que rebota cuando toca el fondo. – George S. Patton`),
  new MsjBienvenida(42, `El fracaso es un requisito para el éxito. Si quieres triunfar rápido, duplica el número de tus fracasos. – Brian Tracy`),
  new MsjBienvenida(43, `El éxito consiste en obtener lo que se desea. La felicidad, en disfrutar lo que se obtiene. – Henry Ford`),
  new MsjBienvenida(44, `El único sitio donde el éxito llega antes que el trabajo es en el diccionario. – Vidal Sassoon`),
  new MsjBienvenida(45, `No hay atajos para conseguir el éxito. Empieza antes, trabaja más duro, y termina más tarde. – Brian Tracy`),
  new MsjBienvenida(46, `El éxito consiste en hacer cosas ordinarias de manera extraordinaria. – Jim Rohn`),
  new MsjBienvenida(47, `Intenta no volverte un hombre de éxito, sino un hombre de valor. – Albert Einstein`),
  new MsjBienvenida(48, `Si deseas el éxito, no lo busques. Limítate a hacer lo que amas y lo que crees. El éxito vendrá por añadidura.`),
  new MsjBienvenida(49, `El éxito no es la clave de la felicidad. La felicidad es la clave del éxito. – Herman Cain`),
  new MsjBienvenida(50, `Elige un trabajo que te guste y no tendrás que trabajar ni un día de tu vida. – Confucio`),
  new MsjBienvenida(51, `He fallado una y otra vez en mi vida. Esa es la razón principal de mi éxito. – Michael Jordan`),
  new MsjBienvenida(52, `Ningún éxito en la vida recompensa el fracaso en el hogar. – David O Mckay`),
  new MsjBienvenida(53, `Cuanto más entreno, más suerte tengo. – Gary Player`),
  new MsjBienvenida(54, `El éxito es simplemente la aplicación diaria de la disciplina. – Jim Rohn`),
  new MsjBienvenida(55, `El fracaso es una parte importante del éxito.`),
  new MsjBienvenida(56, `Los grandes logros nacen de grandes sacrificios, y nunca son fruto del egoísmo. – Napoleon Hill`),
  new MsjBienvenida(57, `Éxito es caminar de un fallo a otro sin perder el entusiasmo. – Winston Churchill`),
];
